INSERT INTO subjects (name) VALUES ('Conjuntos');
INSERT INTO subjects (name) VALUES ('Sequência');
INSERT INTO subjects (name) VALUES ('Progressão Aritmética');
INSERT INTO subjects (name) VALUES ('Progessão Geométrica');
INSERT INTO subjects (name) VALUES ('Matemática Financeira');
INSERT INTO subjects (name) VALUES ('Juros Simples');
INSERT INTO subjects (name) VALUES ('Juros Compostos');
INSERT INTO subjects (name) VALUES ('Análise Combinatória');
INSERT INTO subjects (name) VALUES ('Arranjo');
INSERT INTO subjects (name) VALUES ('Combinação');
INSERT INTO subjects (name) VALUES ('Permutação');
INSERT INTO subjects (name) VALUES ('Probabilidade');
INSERT INTO subjects (name) VALUES ('Estatística');
INSERT INTO subjects (name) VALUES ('Matrizes');
INSERT INTO subjects (name) VALUES ('Tabela');
INSERT INTO subjects (name) VALUES ('Sentenças Matemáticas');
INSERT INTO subjects (name) VALUES ('Funções');
INSERT INTO subjects (name) VALUES ('Função do 1º Grau');
INSERT INTO subjects (name) VALUES ('Função do 2º Grau');
INSERT INTO subjects (name) VALUES ('Gráficos');
INSERT INTO subjects (name) VALUES ('Lei da Função');
INSERT INTO subjects (name) VALUES ('Coeficiente Angular');
INSERT INTO subjects (name) VALUES ('Regra de Três');
INSERT INTO subjects (name) VALUES ('Vértice');
INSERT INTO subjects (name) VALUES ('Receita, Custo, Lucro');
INSERT INTO subjects (name) VALUES ('Função Exponencial');
INSERT INTO subjects (name) VALUES ('Logaritmo');
INSERT INTO subjects (name) VALUES ('Matemática Básica');
INSERT INTO subjects (name) VALUES ('Frações');
INSERT INTO subjects (name) VALUES ('Porcentagem');
INSERT INTO subjects (name) VALUES ('Números Decimais');
INSERT INTO subjects (name) VALUES ('Conversão de Unidades');
INSERT INTO subjects (name) VALUES ('Geometria');
INSERT INTO subjects (name) VALUES ('Geometria Plana');
INSERT INTO subjects (name) VALUES ('Geometria Espacial');
INSERT INTO subjects (name) VALUES ('Plano Cartesiano');
INSERT INTO subjects (name) VALUES ('Identificação de Figuras');
INSERT INTO subjects (name) VALUES ('Movimentação no Espaço');
INSERT INTO subjects (name) VALUES ('Projeção Ortogonal');
INSERT INTO subjects (name) VALUES ('Trigonometria');
INSERT INTO subjects (name) VALUES ('Teorema de Pitágoras');
INSERT INTO subjects (name) VALUES ('Comparação de Volumes');
INSERT INTO subjects (name) VALUES ('Razão e Proporção');
INSERT INTO subjects (name) VALUES ('Comparação de Razões');
INSERT INTO subjects (name) VALUES ('Escala');
INSERT INTO subjects (name) VALUES ('Grandezas Proporcionais');