FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

COPY pom.xml .

RUN mvn dependency:go-offline -B && mvn dependency:resolve-plugins dependency:resolve

EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dmaven.test.skip=true"]