export enum CLASS_GROUP {
  SIMULADO_PRESENCIAL = "SIMULADO_PRESENCIAL",
  EXTENSIVO_ONLINE = "EXTENSIVO_ONLINE",
  SIMULADO_ONLINE = "SIMULADO_ONLINE",
  INTENSIVO_PRESENCIAL = "INTENSIVO_PRESENCIAL",
  INTENSIVO_ONLINE = "INTENSIVO_ONLINE",
}
