/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './router/__root'
import { Route as LogoutRouteImport } from './router/logout'
import { Route as UsuariosIndexRouteImport } from './router/usuarios/index'
import { Route as PerfisIndexRouteImport } from './router/perfis/index'
import { Route as LoginIndexRouteImport } from './router/login/index'
import { Route as PerfisNovoPerfilRouteImport } from './router/perfis/novo-perfil'
import { Route as UsuariosVisualizarUsuarioIdRouteImport } from './router/usuarios/visualizar-usuario/$id'
import { Route as UsuariosEditarUsuarioIdRouteImport } from './router/usuarios/editar-usuario/$id'
import { Route as PerfisVisualizarPerfilIdRouteImport } from './router/perfis/visualizar-perfil/$id'
import { Route as PerfisEditarPerfilIdRouteImport } from './router/perfis/editar-perfil/$id'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIndexRoute = UsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisIndexRoute = PerfisIndexRouteImport.update({
  id: '/perfis/',
  path: '/perfis/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisNovoPerfilRoute = PerfisNovoPerfilRouteImport.update({
  id: '/perfis/novo-perfil',
  path: '/perfis/novo-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosVisualizarUsuarioIdRoute =
  UsuariosVisualizarUsuarioIdRouteImport.update({
    id: '/usuarios/visualizar-usuario/$id',
    path: '/usuarios/visualizar-usuario/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsuariosEditarUsuarioIdRoute = UsuariosEditarUsuarioIdRouteImport.update({
  id: '/usuarios/editar-usuario/$id',
  path: '/usuarios/editar-usuario/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisVisualizarPerfilIdRoute =
  PerfisVisualizarPerfilIdRouteImport.update({
    id: '/perfis/visualizar-perfil/$id',
    path: '/perfis/visualizar-perfil/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const PerfisEditarPerfilIdRoute = PerfisEditarPerfilIdRouteImport.update({
  id: '/perfis/editar-perfil/$id',
  path: '/perfis/editar-perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/logout': typeof LogoutRoute
  '/perfis/novo-perfil': typeof PerfisNovoPerfilRoute
  '/login': typeof LoginIndexRoute
  '/perfis': typeof PerfisIndexRoute
  '/usuarios': typeof UsuariosIndexRoute
  '/perfis/editar-perfil/$id': typeof PerfisEditarPerfilIdRoute
  '/perfis/visualizar-perfil/$id': typeof PerfisVisualizarPerfilIdRoute
  '/usuarios/editar-usuario/$id': typeof UsuariosEditarUsuarioIdRoute
  '/usuarios/visualizar-usuario/$id': typeof UsuariosVisualizarUsuarioIdRoute
}
export interface FileRoutesByTo {
  '/logout': typeof LogoutRoute
  '/perfis/novo-perfil': typeof PerfisNovoPerfilRoute
  '/login': typeof LoginIndexRoute
  '/perfis': typeof PerfisIndexRoute
  '/usuarios': typeof UsuariosIndexRoute
  '/perfis/editar-perfil/$id': typeof PerfisEditarPerfilIdRoute
  '/perfis/visualizar-perfil/$id': typeof PerfisVisualizarPerfilIdRoute
  '/usuarios/editar-usuario/$id': typeof UsuariosEditarUsuarioIdRoute
  '/usuarios/visualizar-usuario/$id': typeof UsuariosVisualizarUsuarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/logout': typeof LogoutRoute
  '/perfis/novo-perfil': typeof PerfisNovoPerfilRoute
  '/login/': typeof LoginIndexRoute
  '/perfis/': typeof PerfisIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
  '/perfis/editar-perfil/$id': typeof PerfisEditarPerfilIdRoute
  '/perfis/visualizar-perfil/$id': typeof PerfisVisualizarPerfilIdRoute
  '/usuarios/editar-usuario/$id': typeof UsuariosEditarUsuarioIdRoute
  '/usuarios/visualizar-usuario/$id': typeof UsuariosVisualizarUsuarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/logout'
    | '/perfis/novo-perfil'
    | '/login'
    | '/perfis'
    | '/usuarios'
    | '/perfis/editar-perfil/$id'
    | '/perfis/visualizar-perfil/$id'
    | '/usuarios/editar-usuario/$id'
    | '/usuarios/visualizar-usuario/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logout'
    | '/perfis/novo-perfil'
    | '/login'
    | '/perfis'
    | '/usuarios'
    | '/perfis/editar-perfil/$id'
    | '/perfis/visualizar-perfil/$id'
    | '/usuarios/editar-usuario/$id'
    | '/usuarios/visualizar-usuario/$id'
  id:
    | '__root__'
    | '/logout'
    | '/perfis/novo-perfil'
    | '/login/'
    | '/perfis/'
    | '/usuarios/'
    | '/perfis/editar-perfil/$id'
    | '/perfis/visualizar-perfil/$id'
    | '/usuarios/editar-usuario/$id'
    | '/usuarios/visualizar-usuario/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LogoutRoute: typeof LogoutRoute
  PerfisNovoPerfilRoute: typeof PerfisNovoPerfilRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PerfisIndexRoute: typeof PerfisIndexRoute
  UsuariosIndexRoute: typeof UsuariosIndexRoute
  PerfisEditarPerfilIdRoute: typeof PerfisEditarPerfilIdRoute
  PerfisVisualizarPerfilIdRoute: typeof PerfisVisualizarPerfilIdRoute
  UsuariosEditarUsuarioIdRoute: typeof UsuariosEditarUsuarioIdRoute
  UsuariosVisualizarUsuarioIdRoute: typeof UsuariosVisualizarUsuarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/': {
      id: '/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis/': {
      id: '/perfis/'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis/novo-perfil': {
      id: '/perfis/novo-perfil'
      path: '/perfis/novo-perfil'
      fullPath: '/perfis/novo-perfil'
      preLoaderRoute: typeof PerfisNovoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/visualizar-usuario/$id': {
      id: '/usuarios/visualizar-usuario/$id'
      path: '/usuarios/visualizar-usuario/$id'
      fullPath: '/usuarios/visualizar-usuario/$id'
      preLoaderRoute: typeof UsuariosVisualizarUsuarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/editar-usuario/$id': {
      id: '/usuarios/editar-usuario/$id'
      path: '/usuarios/editar-usuario/$id'
      fullPath: '/usuarios/editar-usuario/$id'
      preLoaderRoute: typeof UsuariosEditarUsuarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis/visualizar-perfil/$id': {
      id: '/perfis/visualizar-perfil/$id'
      path: '/perfis/visualizar-perfil/$id'
      fullPath: '/perfis/visualizar-perfil/$id'
      preLoaderRoute: typeof PerfisVisualizarPerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis/editar-perfil/$id': {
      id: '/perfis/editar-perfil/$id'
      path: '/perfis/editar-perfil/$id'
      fullPath: '/perfis/editar-perfil/$id'
      preLoaderRoute: typeof PerfisEditarPerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LogoutRoute: LogoutRoute,
  PerfisNovoPerfilRoute: PerfisNovoPerfilRoute,
  LoginIndexRoute: LoginIndexRoute,
  PerfisIndexRoute: PerfisIndexRoute,
  UsuariosIndexRoute: UsuariosIndexRoute,
  PerfisEditarPerfilIdRoute: PerfisEditarPerfilIdRoute,
  PerfisVisualizarPerfilIdRoute: PerfisVisualizarPerfilIdRoute,
  UsuariosEditarUsuarioIdRoute: UsuariosEditarUsuarioIdRoute,
  UsuariosVisualizarUsuarioIdRoute: UsuariosVisualizarUsuarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
